AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  hybridRetrieval

  Sample SAM Template for hybridRetrieval

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 180

Resources:
  hybridRetrievalFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hybridRetrieval/
      Handler: app.lambda_handler
      Runtime: python3.11
      AutoPublishAlias: Live
      Architectures:
        - x86_64
      Events:
        hybridRetrieval:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hybridRetrieval
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  hybridRetrievalAPI:
    Description: "API Gateway endpoint URL for Prod stage for HybridRetrieval function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hybridRetrieval/"
  hybridRetrievalFunction:
    Description: "HybridRetrieval Lambda Function ARN"
    Value: !GetAtt hybridRetrievalFunction.Arn
  hybridRetrievalFunctionIamRole:
    Description: "Implicit IAM Role created for hybridRetrieval function"
    Value: !GetAtt hybridRetrievalFunctionRole.Arn
